window.MusiqData = {
  songs: [
    {
      id: 'song-1',
      title: 'Midnight Signal',
      artistId: 'artist-1',
      artist: 'Lina Vale',
      albumId: 'album-1',
      album: 'Neon Reverie',
      genre: 'Electronic',
      duration: '3:42',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-2',
      title: 'Blue Voltage',
      artistId: 'artist-1',
      artist: 'Lina Vale',
      albumId: 'album-1',
      album: 'Neon Reverie',
      genre: 'Electronic',
      duration: '4:08',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-3',
      title: 'Afterglow',
      artistId: 'artist-2',
      artist: 'Prisha K.',
      albumId: 'album-2',
      album: 'Afterglow',
      genre: 'Indie Pop',
      duration: '3:36',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-4',
      title: 'Paper Moons',
      artistId: 'artist-2',
      artist: 'Prisha K.',
      albumId: 'album-2',
      album: 'Afterglow',
      genre: 'Indie Pop',
      duration: '3:51',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-5',
      title: 'Faded Haze',
      artistId: 'artist-3',
      artist: 'Arjun M.',
      albumId: 'album-3',
      album: 'Faded Haze',
      genre: 'Lo-Fi',
      duration: '2:58',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-6',
      title: 'Window Seat',
      artistId: 'artist-3',
      artist: 'Arjun M.',
      albumId: 'album-3',
      album: 'Faded Haze',
      genre: 'Lo-Fi',
      duration: '3:14',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-7',
      title: 'Glass Sky',
      artistId: 'artist-4',
      artist: 'Nova Lane',
      albumId: 'album-4',
      album: 'Glass Sky',
      genre: 'Ambient',
      duration: '4:22',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-8',
      title: 'Soft Focus',
      artistId: 'artist-4',
      artist: 'Nova Lane',
      albumId: 'album-4',
      album: 'Glass Sky',
      genre: 'Ambient',
      duration: '3:47',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-9',
      title: 'Signal Bloom',
      artistId: 'artist-5',
      artist: 'Rhea S.',
      albumId: 'album-5',
      album: 'Signal Bloom',
      genre: 'Alternative',
      duration: '3:29',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-10',
      title: 'Static Hearts',
      artistId: 'artist-5',
      artist: 'Rhea S.',
      albumId: 'album-5',
      album: 'Signal Bloom',
      genre: 'Alternative',
      duration: '3:55',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-11',
      title: 'Night Pulse',
      artistId: 'artist-6',
      artist: 'Vanta',
      albumId: 'album-6',
      album: 'Night Pulse',
      genre: 'Hip-Hop',
      duration: '2:46',
      src: 'assets/audio/test.mp3',
    },
    {
      id: 'song-12',
      title: 'Low Orbit',
      artistId: 'artist-6',
      artist: 'Vanta',
      albumId: 'album-6',
      album: 'Night Pulse',
      genre: 'Hip-Hop',
      duration: '3:18',
      src: 'assets/audio/test.mp3',
    },
  ],
  albums: [
    { id: 'album-1', title: 'Neon Reverie', artistId: 'artist-1', artist: 'Lina Vale', genre: 'Electronic' },
    { id: 'album-2', title: 'Afterglow', artistId: 'artist-2', artist: 'Prisha K.', genre: 'Indie Pop' },
    { id: 'album-3', title: 'Faded Haze', artistId: 'artist-3', artist: 'Arjun M.', genre: 'Lo-Fi' },
    { id: 'album-4', title: 'Glass Sky', artistId: 'artist-4', artist: 'Nova Lane', genre: 'Ambient' },
    { id: 'album-5', title: 'Signal Bloom', artistId: 'artist-5', artist: 'Rhea S.', genre: 'Alternative' },
    { id: 'album-6', title: 'Night Pulse', artistId: 'artist-6', artist: 'Vanta', genre: 'Hip-Hop' },
  ],
  artists: [
    { id: 'artist-1', name: 'Lina Vale', followers: '58k' },
    { id: 'artist-2', name: 'Prisha K.', followers: '92k' },
    { id: 'artist-3', name: 'Arjun M.', followers: '71k' },
    { id: 'artist-4', name: 'Nova Lane', followers: '44k' },
    { id: 'artist-5', name: 'Rhea S.', followers: '63k' },
    { id: 'artist-6', name: 'Vanta', followers: '85k' },
  ],
  genres: [
    { id: 'genre-1', name: 'Electronic' },
    { id: 'genre-2', name: 'Indie Pop' },
    { id: 'genre-3', name: 'Lo-Fi' },
    { id: 'genre-4', name: 'Ambient' },
    { id: 'genre-5', name: 'Alternative' },
    { id: 'genre-6', name: 'Hip-Hop' },
  ],
  playlists: [
    {
      id: 'playlist-1',
      name: 'Late Night Coding',
      description: 'Steady sounds for focused coding sessions',
      songIds: ['song-1', 'song-5', 'song-7', 'song-12'],
    },
    {
      id: 'playlist-2',
      name: 'Soft Landing',
      description: 'A quieter soundtrack for winding down',
      songIds: ['song-3', 'song-6', 'song-8', 'song-9'],
    },
    {
      id: 'playlist-3',
      name: 'City After Dark',
      description: 'Electronic beats and late-night energy',
      songIds: ['song-1', 'song-2', 'song-11', 'song-12'],
    },
    {
      id: 'playlist-4',
      name: 'Fresh Perspective',
      description: 'Indie and alternative tracks for a reset',
      songIds: ['song-3', 'song-4', 'song-9', 'song-10'],
    },
  ],
};